name: Master CI/CD

on:
  push:
    branches-ignore:
      - 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - run: npm audit
    - run: npm run lint
    - run: npm test
